function [NCDF,grib] = nomadGFS(grib,simulation)

for i=1:grib.hours+1
    grib.file_name = "gfs."+year(grib.start)+num2str(month(grib.start),'%02.f')+num2str(day(grib.start),'%02.f')+"/"+num2str(hour(grib.start),'%02.f')+"/atmos/"+"gfs.t"+num2str(hour(grib.start),'%02.f')+"z.pgrb2.0p25.f"+num2str(i-1,'%03.f');
    grib.ncfilename = "forcast\nc\" +year(grib.start)+num2str(month(grib.start),'%02.f')+num2str(day(grib.start),'%02.f')+"_"+num2str(hour(grib.start),'%02.f')+'nomad.nc';
    url = 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/'+grib.file_name;
    filename = "forcast\"+year(grib.start)+num2str(month(grib.start),'%02.f')+num2str(day(grib.start),'%02.f')+"_"+num2str(hour(grib.start),'%02.f')+'nomad.grib';
    sprintf("Downloading grib: "+year(grib.start)+num2str(month(grib.start),'%02.f')+num2str(day(grib.start),'%02.f')+"_"+num2str(hour(grib.start),'%02.f')+'nomad.grib')
    grib.outfilename = websave(filename,url);
    grib.ncfilename = "forcast\nc\" +year(grib.start)+num2str(month(grib.start),'%02.f')+num2str(day(grib.start),'%02.f')+"_"+num2str(hour(grib.start),'%02.f')+'nomad.nc';
    wgrib2cmd= "wgrib2"+' -match ":HGT:|:UGRD:|:VGRD:|:TMP:|:ALBDO:" '+convertCharsToStrings(grib.outfilename)+' -netcdf ' + grib.ncfilename;
    system(wgrib2cmd);
    NCDF.info(i) = ncinfo(grib.ncfilename);
    NCDF.Lat = ncread(grib.ncfilename,'latitude');
    NCDF.Lon = ncread(grib.ncfilename,'longitude');
    NCDF.hour(i) = i-1;
    NCDF = UGRDread(grib,NCDF,i);
    NCDF = VGRDread(grib,NCDF,i);
    NCDF = HGTread(grib,NCDF,i);
    NCDF = TMPread(grib,NCDF,i);
    
end
NCDF.matfilename = "forcast\mat\" +year(grib.start)+num2str(month(grib.start),'%02.f')+num2str(day(grib.start),'%02.f')+"_"+num2str(hour(grib.start),'%02.f')+'nomad.mat';
save(NCDF.matfilename,'NCDF', '-v7.3')
end


function NCDF = UGRDread(grib,NCDF,i)
    NCDF.UGRD(:,:,i,1) = ncread(grib.ncfilename,'UGRD_0D01mb');
    NCDF.UGRD(:,:,i,2) = ncread(grib.ncfilename,'UGRD_0D02mb');
    NCDF.UGRD(:,:,i,3) = ncread(grib.ncfilename,'UGRD_0D04mb');
    NCDF.UGRD(:,:,i,4) = ncread(grib.ncfilename,'UGRD_0D07mb');
    NCDF.UGRD(:,:,i,5) = ncread(grib.ncfilename,'UGRD_0D1mb');
    NCDF.UGRD(:,:,i,6) = ncread(grib.ncfilename,'UGRD_0D2mb');
    NCDF.UGRD(:,:,i,7) = ncread(grib.ncfilename,'UGRD_0D4mb');
    NCDF.UGRD(:,:,i,8) = ncread(grib.ncfilename,'UGRD_0D7mb');
    NCDF.UGRD(:,:,i,9) = ncread(grib.ncfilename,'UGRD_1mb');
    NCDF.UGRD(:,:,i,10) = ncread(grib.ncfilename,'UGRD_2mb');
    NCDF.UGRD(:,:,i,11) = ncread(grib.ncfilename,'UGRD_3mb');
    NCDF.UGRD(:,:,i,12) = ncread(grib.ncfilename,'UGRD_5mb');
    NCDF.UGRD(:,:,i,13) = ncread(grib.ncfilename,'UGRD_7mb');
    NCDF.UGRD(:,:,i,14) = ncread(grib.ncfilename,'UGRD_10mb');
    NCDF.UGRD(:,:,i,15) = ncread(grib.ncfilename,'UGRD_15mb');
    NCDF.UGRD(:,:,i,16) = ncread(grib.ncfilename,'UGRD_20mb');
    NCDF.UGRD(:,:,i,17) = ncread(grib.ncfilename,'UGRD_30mb');
    NCDF.UGRD(:,:,i,18) = ncread(grib.ncfilename,'UGRD_40mb');
    NCDF.UGRD(:,:,i,19) = ncread(grib.ncfilename,'UGRD_50mb');
    NCDF.UGRD(:,:,i,20) = ncread(grib.ncfilename,'UGRD_70mb');
    NCDF.UGRD(:,:,i,21) = ncread(grib.ncfilename,'UGRD_100mb');
    NCDF.UGRD(:,:,i,22) = ncread(grib.ncfilename,'UGRD_150mb');
    NCDF.UGRD(:,:,i,23) = ncread(grib.ncfilename,'UGRD_200mb');
    NCDF.UGRD(:,:,i,24) = ncread(grib.ncfilename,'UGRD_250mb');
    NCDF.UGRD(:,:,i,25) = ncread(grib.ncfilename,'UGRD_300mb');
    NCDF.UGRD(:,:,i,26) = ncread(grib.ncfilename,'UGRD_350mb');
    NCDF.UGRD(:,:,i,27) = ncread(grib.ncfilename,'UGRD_400mb');
    NCDF.UGRD(:,:,i,28) = ncread(grib.ncfilename,'UGRD_450mb');
    NCDF.UGRD(:,:,i,29) = ncread(grib.ncfilename,'UGRD_500mb');
    NCDF.UGRD(:,:,i,30) = ncread(grib.ncfilename,'UGRD_550mb');
    NCDF.UGRD(:,:,i,31) = ncread(grib.ncfilename,'UGRD_600mb');
    NCDF.UGRD(:,:,i,32) = ncread(grib.ncfilename,'UGRD_650mb');
    NCDF.UGRD(:,:,i,33) = ncread(grib.ncfilename,'UGRD_700mb');
    NCDF.UGRD(:,:,i,34) = ncread(grib.ncfilename,'UGRD_750mb');
    NCDF.UGRD(:,:,i,35) = ncread(grib.ncfilename,'UGRD_800mb');
    NCDF.UGRD(:,:,i,36) = ncread(grib.ncfilename,'UGRD_850mb');
    NCDF.UGRD(:,:,i,37) = ncread(grib.ncfilename,'UGRD_900mb');
    NCDF.UGRD(:,:,i,38) = ncread(grib.ncfilename,'UGRD_925mb');
    NCDF.UGRD(:,:,i,39) = ncread(grib.ncfilename,'UGRD_950mb');
    NCDF.UGRD(:,:,i,40) = ncread(grib.ncfilename,'UGRD_975mb');
    NCDF.UGRD(:,:,i,41) = ncread(grib.ncfilename,'UGRD_1000mb');
end

function NCDF = VGRDread(grib,NCDF,i)
    NCDF.VGRD(:,:,i,1) = ncread(grib.ncfilename,'VGRD_0D01mb');
    NCDF.VGRD(:,:,i,2) = ncread(grib.ncfilename,'VGRD_0D02mb');
    NCDF.VGRD(:,:,i,3) = ncread(grib.ncfilename,'VGRD_0D04mb');
    NCDF.VGRD(:,:,i,4) = ncread(grib.ncfilename,'VGRD_0D07mb');
    NCDF.VGRD(:,:,i,5) = ncread(grib.ncfilename,'VGRD_0D1mb');
    NCDF.VGRD(:,:,i,6) = ncread(grib.ncfilename,'VGRD_0D2mb');
    NCDF.VGRD(:,:,i,7) = ncread(grib.ncfilename,'VGRD_0D4mb');
    NCDF.VGRD(:,:,i,8) = ncread(grib.ncfilename,'VGRD_0D7mb');
    NCDF.VGRD(:,:,i,9) = ncread(grib.ncfilename,'VGRD_1mb');
    NCDF.VGRD(:,:,i,10) = ncread(grib.ncfilename,'VGRD_2mb');
    NCDF.VGRD(:,:,i,11) = ncread(grib.ncfilename,'VGRD_3mb');
    NCDF.VGRD(:,:,i,12) = ncread(grib.ncfilename,'VGRD_5mb');
    NCDF.VGRD(:,:,i,13) = ncread(grib.ncfilename,'VGRD_7mb');
    NCDF.VGRD(:,:,i,14) = ncread(grib.ncfilename,'VGRD_10mb');
    NCDF.VGRD(:,:,i,15) = ncread(grib.ncfilename,'VGRD_15mb');
    NCDF.VGRD(:,:,i,16) = ncread(grib.ncfilename,'VGRD_20mb');
    NCDF.VGRD(:,:,i,17) = ncread(grib.ncfilename,'VGRD_30mb');
    NCDF.VGRD(:,:,i,18) = ncread(grib.ncfilename,'VGRD_40mb');
    NCDF.VGRD(:,:,i,19) = ncread(grib.ncfilename,'VGRD_50mb');
    NCDF.VGRD(:,:,i,20) = ncread(grib.ncfilename,'VGRD_70mb');
    NCDF.VGRD(:,:,i,21) = ncread(grib.ncfilename,'VGRD_100mb');
    NCDF.VGRD(:,:,i,22) = ncread(grib.ncfilename,'VGRD_150mb');
    NCDF.VGRD(:,:,i,23) = ncread(grib.ncfilename,'VGRD_200mb');
    NCDF.VGRD(:,:,i,24) = ncread(grib.ncfilename,'VGRD_250mb');
    NCDF.VGRD(:,:,i,25) = ncread(grib.ncfilename,'VGRD_300mb');
    NCDF.VGRD(:,:,i,26) = ncread(grib.ncfilename,'VGRD_350mb');
    NCDF.VGRD(:,:,i,27) = ncread(grib.ncfilename,'VGRD_400mb');
    NCDF.VGRD(:,:,i,28) = ncread(grib.ncfilename,'VGRD_450mb');
    NCDF.VGRD(:,:,i,29) = ncread(grib.ncfilename,'VGRD_500mb');
    NCDF.VGRD(:,:,i,30) = ncread(grib.ncfilename,'VGRD_550mb');
    NCDF.VGRD(:,:,i,31) = ncread(grib.ncfilename,'VGRD_600mb');
    NCDF.VGRD(:,:,i,32) = ncread(grib.ncfilename,'VGRD_650mb');
    NCDF.VGRD(:,:,i,33) = ncread(grib.ncfilename,'VGRD_700mb');
    NCDF.VGRD(:,:,i,34) = ncread(grib.ncfilename,'VGRD_750mb');
    NCDF.VGRD(:,:,i,35) = ncread(grib.ncfilename,'VGRD_800mb');
    NCDF.VGRD(:,:,i,36) = ncread(grib.ncfilename,'VGRD_850mb');
    NCDF.VGRD(:,:,i,37) = ncread(grib.ncfilename,'VGRD_900mb');
    NCDF.VGRD(:,:,i,38) = ncread(grib.ncfilename,'VGRD_925mb');
    NCDF.VGRD(:,:,i,39) = ncread(grib.ncfilename,'VGRD_950mb');
    NCDF.VGRD(:,:,i,40) = ncread(grib.ncfilename,'VGRD_975mb');
    NCDF.VGRD(:,:,i,41) = ncread(grib.ncfilename,'VGRD_1000mb');
end

function NCDF = HGTread(grib,NCDF,i)
    NCDF.HGT(:,:,i,1) = ncread(grib.ncfilename,'HGT_0D01mb');
    NCDF.HGT(:,:,i,2) = ncread(grib.ncfilename,'HGT_0D02mb');
    NCDF.HGT(:,:,i,3) = ncread(grib.ncfilename,'HGT_0D04mb');
    NCDF.HGT(:,:,i,4) = ncread(grib.ncfilename,'HGT_0D07mb');
    NCDF.HGT(:,:,i,5) = ncread(grib.ncfilename,'HGT_0D1mb');
    NCDF.HGT(:,:,i,6) = ncread(grib.ncfilename,'HGT_0D2mb');
    NCDF.HGT(:,:,i,7) = ncread(grib.ncfilename,'HGT_0D4mb');
    NCDF.HGT(:,:,i,8) = ncread(grib.ncfilename,'HGT_0D7mb');
    NCDF.HGT(:,:,i,9) = ncread(grib.ncfilename,'HGT_1mb');
    NCDF.HGT(:,:,i,10) = ncread(grib.ncfilename,'HGT_2mb');
    NCDF.HGT(:,:,i,11) = ncread(grib.ncfilename,'HGT_3mb');
    NCDF.HGT(:,:,i,12) = ncread(grib.ncfilename,'HGT_5mb');
    NCDF.HGT(:,:,i,13) = ncread(grib.ncfilename,'HGT_7mb');
    NCDF.HGT(:,:,i,14) = ncread(grib.ncfilename,'HGT_10mb');
    NCDF.HGT(:,:,i,15) = ncread(grib.ncfilename,'HGT_15mb');
    NCDF.HGT(:,:,i,16) = ncread(grib.ncfilename,'HGT_20mb');
    NCDF.HGT(:,:,i,17) = ncread(grib.ncfilename,'HGT_30mb');
    NCDF.HGT(:,:,i,18) = ncread(grib.ncfilename,'HGT_40mb');
    NCDF.HGT(:,:,i,19) = ncread(grib.ncfilename,'HGT_50mb');
    NCDF.HGT(:,:,i,20) = ncread(grib.ncfilename,'HGT_70mb');
    NCDF.HGT(:,:,i,21) = ncread(grib.ncfilename,'HGT_100mb');
    NCDF.HGT(:,:,i,22) = ncread(grib.ncfilename,'HGT_150mb');
    NCDF.HGT(:,:,i,23) = ncread(grib.ncfilename,'HGT_200mb');
    NCDF.HGT(:,:,i,24) = ncread(grib.ncfilename,'HGT_250mb');
    NCDF.HGT(:,:,i,25) = ncread(grib.ncfilename,'HGT_300mb');
    NCDF.HGT(:,:,i,26) = ncread(grib.ncfilename,'HGT_350mb');
    NCDF.HGT(:,:,i,27) = ncread(grib.ncfilename,'HGT_400mb');
    NCDF.HGT(:,:,i,28) = ncread(grib.ncfilename,'HGT_450mb');
    NCDF.HGT(:,:,i,29) = ncread(grib.ncfilename,'HGT_500mb');
    NCDF.HGT(:,:,i,30) = ncread(grib.ncfilename,'HGT_550mb');
    NCDF.HGT(:,:,i,31) = ncread(grib.ncfilename,'HGT_600mb');
    NCDF.HGT(:,:,i,32) = ncread(grib.ncfilename,'HGT_650mb');
    NCDF.HGT(:,:,i,33) = ncread(grib.ncfilename,'HGT_700mb');
    NCDF.HGT(:,:,i,34) = ncread(grib.ncfilename,'HGT_750mb');
    NCDF.HGT(:,:,i,35) = ncread(grib.ncfilename,'HGT_800mb');
    NCDF.HGT(:,:,i,36) = ncread(grib.ncfilename,'HGT_850mb');
    NCDF.HGT(:,:,i,37) = ncread(grib.ncfilename,'HGT_900mb');
    NCDF.HGT(:,:,i,38) = ncread(grib.ncfilename,'HGT_925mb');
    NCDF.HGT(:,:,i,39) = ncread(grib.ncfilename,'HGT_950mb');
    NCDF.HGT(:,:,i,40) = ncread(grib.ncfilename,'HGT_975mb');
    NCDF.HGT(:,:,i,41) = ncread(grib.ncfilename,'HGT_1000mb');
end

function NCDF = TMPread(grib,NCDF,i)
    NCDF.TMP(:,:,i,1) = ncread(grib.ncfilename,'TMP_0D01mb');
    NCDF.TMP(:,:,i,2) = ncread(grib.ncfilename,'TMP_0D02mb');
    NCDF.TMP(:,:,i,3) = ncread(grib.ncfilename,'TMP_0D04mb');
    NCDF.TMP(:,:,i,4) = ncread(grib.ncfilename,'TMP_0D07mb');
    NCDF.TMP(:,:,i,5) = ncread(grib.ncfilename,'TMP_0D1mb');
    NCDF.TMP(:,:,i,6) = ncread(grib.ncfilename,'TMP_0D2mb');
    NCDF.TMP(:,:,i,7) = ncread(grib.ncfilename,'TMP_0D4mb');
    NCDF.TMP(:,:,i,8) = ncread(grib.ncfilename,'TMP_0D7mb');
    NCDF.TMP(:,:,i,9) = ncread(grib.ncfilename,'TMP_1mb');
    NCDF.TMP(:,:,i,10) = ncread(grib.ncfilename,'TMP_2mb');
    NCDF.TMP(:,:,i,11) = ncread(grib.ncfilename,'TMP_3mb');
    NCDF.TMP(:,:,i,12) = ncread(grib.ncfilename,'TMP_5mb');
    NCDF.TMP(:,:,i,13) = ncread(grib.ncfilename,'TMP_7mb');
    NCDF.TMP(:,:,i,14) = ncread(grib.ncfilename,'TMP_10mb');
    NCDF.TMP(:,:,i,15) = ncread(grib.ncfilename,'TMP_15mb');
    NCDF.TMP(:,:,i,16) = ncread(grib.ncfilename,'TMP_20mb');
    NCDF.TMP(:,:,i,17) = ncread(grib.ncfilename,'TMP_30mb');
    NCDF.TMP(:,:,i,18) = ncread(grib.ncfilename,'TMP_40mb');
    NCDF.TMP(:,:,i,19) = ncread(grib.ncfilename,'TMP_50mb');
    NCDF.TMP(:,:,i,20) = ncread(grib.ncfilename,'TMP_70mb');
    NCDF.TMP(:,:,i,21) = ncread(grib.ncfilename,'TMP_100mb');
    NCDF.TMP(:,:,i,22) = ncread(grib.ncfilename,'TMP_150mb');
    NCDF.TMP(:,:,i,23) = ncread(grib.ncfilename,'TMP_200mb');
    NCDF.TMP(:,:,i,24) = ncread(grib.ncfilename,'TMP_250mb');
    NCDF.TMP(:,:,i,25) = ncread(grib.ncfilename,'TMP_300mb');
    NCDF.TMP(:,:,i,26) = ncread(grib.ncfilename,'TMP_350mb');
    NCDF.TMP(:,:,i,27) = ncread(grib.ncfilename,'TMP_400mb');
    NCDF.TMP(:,:,i,28) = ncread(grib.ncfilename,'TMP_450mb');
    NCDF.TMP(:,:,i,29) = ncread(grib.ncfilename,'TMP_500mb');
    NCDF.TMP(:,:,i,30) = ncread(grib.ncfilename,'TMP_550mb');
    NCDF.TMP(:,:,i,31) = ncread(grib.ncfilename,'TMP_600mb');
    NCDF.TMP(:,:,i,32) = ncread(grib.ncfilename,'TMP_650mb');
    NCDF.TMP(:,:,i,33) = ncread(grib.ncfilename,'TMP_700mb');
    NCDF.TMP(:,:,i,34) = ncread(grib.ncfilename,'TMP_750mb');
    NCDF.TMP(:,:,i,35) = ncread(grib.ncfilename,'TMP_800mb');
    NCDF.TMP(:,:,i,36) = ncread(grib.ncfilename,'TMP_850mb');
    NCDF.TMP(:,:,i,37) = ncread(grib.ncfilename,'TMP_900mb');
    NCDF.TMP(:,:,i,38) = ncread(grib.ncfilename,'TMP_925mb');
    NCDF.TMP(:,:,i,39) = ncread(grib.ncfilename,'TMP_950mb');
    NCDF.TMP(:,:,i,40) = ncread(grib.ncfilename,'TMP_975mb');
    NCDF.TMP(:,:,i,41) = ncread(grib.ncfilename,'TMP_1000mb');
end